kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: williamchanrico/arzhonid
      tags: latest
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
