kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: williamchanrico/arzhonid
      tags:
        - latest
        - 1.0.2
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
