---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: arzhon-id
  namespace: default
spec:
  secretName: arzhon-id-tls
  issuerRef:
    name: letsencrypt
  commonName: "k8s.arzhon.id"
  dnsNames:
    - k8s.arzhon.id
  acme:
    config:
      - dns01:
          provider: cf-dns
        domains:
          - "k8s.arzhon.id"
